docker/login-action

__tests__/context.test.ts
__tests__/main.test.ts
action.yml
dist/index.js
src/context.ts

Username required

---

.github/workflows/ci.yml
README.md
__tests__/aws.test.ts
dist/index.js
src/aws.ts
src/docker.ts

Fixes #36 
cc. @clarkbw @vincentsarago

Add support for public ECR

---

README.md
__tests__/aws.test.ts
dist/index.js
src/aws.ts
src/docker.ts

Fixes #39 
Fixes docker/build-push-action#253
cc. @michaelb990
@davidski Can be tested with:
```yaml
name: ci
on:
push:
branches: master
jobs:
login:
runs-on: ubuntu-latest
steps:
-
name: Login to ECR
uses: crazy-max/docker-login-action@registry-ids
with:
registry: <aws-account-number>.dkr.ecr.<region>.amazonaws.com
username: ${{ secrets.AWS_ACCESS_KEY_ID }}
password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
env:
AWS_ACCOUNT_IDS: 012345678910,023456789012
```

Handle Amazon ECR registries associated with other accounts

---

README.md

Have been using this action successfully with quay.io for a while now, and while the setup is trivial, I thought it would be useful to add some usage docs.

 Add Quay.io usage docs

---

.github/workflows/ci.yml
__tests__/context.test.ts
__tests__/main.test.ts
dist/index.js
src/context.ts
src/state-helper.ts

Use `core.getBooleanInput`

---

.github/workflows/ci.yml
README.md

Ref. https://github.blog/2021-06-21-github-packages-container-registry-generally-available/

Remove GitHub Packages Docker Registry

---

.github/workflows/ci.yml
README.md

Small changes for GHCR doc

---

.github/workflows/ci.yml

> The ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021. Migrate to ubuntu-latest instead. For more details see https://github.com/actions/virtual-environments/issues/3287

Ubuntu 16.04 runner deprecated

---

README.md

Update instructions for Google registry

---

.github/workflows/ci.yml
__tests__/aws.test.ts
__tests__/context.test.ts
__tests__/docker.test.ts
hack/build.Dockerfile
package.json
src/aws.ts
src/docker.ts
yarn.lock

Follow-up https://github.com/docker/login-action/pull/114#pullrequestreview-834026943
Fixes #125 
@Flydiverny Now using the AWS SDK so we don't need to rely on the AWS CLI.
With this we are also able to authenticate on Windows runners.

ecr: switch implementation to use the AWS SDK

---

.github/workflows/ci.yml
README.md
__tests__/main.test.ts
action.yml
src/context.ts
src/docker.ts
src/main.ts

`ecr` input to specify whether the given registry is ECR

---

__tests__/aws.test.ts
package.json
src/aws.ts
yarn.lock

Related to #126 
> I was thinking maybe we could use the v3 aws-sdk lib instead of the v2 one, ie @aws-sdk/client-ecr and @aws-sdk/client-ecr-public. I tried to make these changes locally but for some reason docker buildx bake validation fails saying there's diffs to output. Seems to be CRLF vs LF issue 😅
> It seemed to reduce the dist size a bit since v3 sdk is modular.

fix(ecr): only set credentials if username & password is specified, refactor to use aws-sdk v3

---

README.md

As keyless authentication is recommended, added instructions for GCR and GAR.
- https://cloud.google.com/container-registry/docs/advanced-authentication#token
- https://cloud.google.com/iam/docs/workload-identity-federation
- https://github.com/google-github-actions/auth#usage
- https://github.com/google-github-actions/auth#setting-up-workload-identity-federation

Update readme with workload identity based authentication for GCR and GAR

---

.github/dependabot.yml

related to:
* https://github.com/github/roadmap/issues/148#issuecomment-1629826280
* https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/

dependabot: group aws-sdk and proxy-agent dependencies

---

.github/workflows/codeql.yml

Adding CodeQL configuration for repo to meet security and compliance requirements
[ESEC-20](https://docker.atlassian.net/browse/ESEC-20)
[ESEC-20]: https://docker.atlassian.net/browse/ESEC-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Introduce codeql.yml to enable SAST scanning

---

.github/workflows/codeql.yml

CodeQL currently scans `dist` folder which contains source code not introduced by this repository and could trigger false-positives. This should only scan `src` folder per https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#specifying-directories-to-scan

ci(codeql): restrict code scanning to src folder

---

.github/workflows/test.yml

related to https://github.com/docker/login-action/actions/runs/7934435026

bump codecov/codecov-action from 3 to 4

---

README.md

Resolves #610 
Tested in the following action setup:
```
name: Build and Push
on:
release:
types: [published]
jobs:
build_and_push:
runs-on: ubuntu-latest
steps:
- name: Checkout the repo 
uses: actions/checkout@v4
- name: Set up Docker Buildx
uses: docker/setup-buildx-action@v3
- name: Extract metadata (tags, labels) for Docker
id: meta
uses: docker/metadata-action@v5
with:
images: registry.digitalocean.com/junderwood/website
- name: Login to DigitalOcean Container Registry
uses: docker/login-action@v3
with:
registry: registry.digitalocean.com
username: ${{ secrets.DIGITALOCEAN_USERNAME }}
password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
- name: Build and push
uses: docker/build-push-action@v5
with:
context: .
platforms: linux/amd64,linux/arm64
file: ./Dockerfile
push: true
tags: ${{ …
```

Update README.md with Digital Ocean example

---

README.md

- **docs: gcr does not support base64-encoded keys**
- **docs: use vars for usernames, not secrets**

README: fix gcr example, use vars for usernames

---

README.md

This fixes an outdated link to the PowerUser section of the AWS ECR IAM Managed Policies documentation page.
Preivous link (redirects to homepage of docs): https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr_managed_policies.html#AmazonEC2ContainerRegistryPowerUser
New Link: https://docs.aws.amazon.com/AmazonECR/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AmazonEC2ContainerRegistryPowerUser

Fix link to AWS ECR PowerUser IAM documentation
